<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageVersion Include="System.Data.SQLite" Version="2.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Handlebars.Net" Version="2.1.6" />
    <PackageVersion Include="McMaster.Extensions.CommandLineUtils" Version="4.1.1" />
    <PackageVersion Include="MySql.Data" Version="9.5.0" />
    <PackageVersion Include="NEST" Version="7.17.5" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Npgsql" Version="10.0.1" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.0" />
    <PackageVersion Include="SmartSql" Version="4.1.68" />
    <PackageVersion Include="SmartSql.Bulk.MySql" Version="4.1.68" />
    <PackageVersion Include="SmartSql.Bulk.PostgreSql" Version="4.1.68" />
    <PackageVersion Include="SmartSql.Bulk.SqlServer" Version="4.1.68" />
    <PackageVersion Include="SmartSql.Options" Version="4.1.68" />
    <PackageVersion Include="SmartSql.TypeHandler" Version="4.1.68" />
    <PackageVersion Include="SmartSql.TypeHandler.PostgreSql" Version="4.1.68" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
