<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NEST" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartCode.ETL\SmartCode.ETL.csproj" />
  </ItemGroup>

</Project>