<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SmartSql.Options" />
    <PackageReference Include="SmartSql.TypeHandler" />
    <PackageReference Include="SmartSql.TypeHandler.PostgreSql" />
    <PackageReference Include="System.Data.SqlClient" />
    <PackageReference Include="System.Data.SQLite" />
    <PackageReference Include="MySql.Data" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartCode.TemplateEngine\SmartCode.TemplateEngine.csproj" />
    <ProjectReference Include="..\SmartCode\SmartCode.csproj" />
  </ItemGroup>

</Project>